//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.15 at 09:54:44 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://restsql.org/schema")
package org.restsql.service.testcase;
