//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.07 at 09:54:01 AM EDT 
//


package org.restsql.service.testcase;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ServiceTestCaseDefinition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceTestCaseDefinition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="setup" type="{http://restsql.org/schema}SetupOrTeardown" minOccurs="0"/>
 *         &lt;element name="step" type="{http://restsql.org/schema}Step" maxOccurs="unbounded"/>
 *         &lt;element name="teardown" type="{http://restsql.org/schema}SetupOrTeardown" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceTestCaseDefinition", propOrder = {
    "setup",
    "step",
    "teardown"
})
public class ServiceTestCaseDefinition {

    protected SetupOrTeardown setup;
    @XmlElement(required = true)
    protected List<Step> step;
    protected SetupOrTeardown teardown;

    /**
     * Gets the value of the setup property.
     * 
     * @return
     *     possible object is
     *     {@link SetupOrTeardown }
     *     
     */
    public SetupOrTeardown getSetup() {
        return setup;
    }

    /**
     * Sets the value of the setup property.
     * 
     * @param value
     *     allowed object is
     *     {@link SetupOrTeardown }
     *     
     */
    public void setSetup(SetupOrTeardown value) {
        this.setup = value;
    }

    /**
     * Gets the value of the step property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the step property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStep().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Step }
     * 
     * 
     */
    public List<Step> getStep() {
        if (step == null) {
            step = new ArrayList<Step>();
        }
        return this.step;
    }

    /**
     * Gets the value of the teardown property.
     * 
     * @return
     *     possible object is
     *     {@link SetupOrTeardown }
     *     
     */
    public SetupOrTeardown getTeardown() {
        return teardown;
    }

    /**
     * Sets the value of the teardown property.
     * 
     * @param value
     *     allowed object is
     *     {@link SetupOrTeardown }
     *     
     */
    public void setTeardown(SetupOrTeardown value) {
        this.teardown = value;
    }

}
